### ISSUE TITLE
此项目将在近期重写

### ISSUE THREAD

**Issue by jerryshell** [grpcman/grpcman#10]
此项目原本是我们两位作者在先前工作的简单总结

由于 Electron 的频繁更新，加之自从我们离开先前的工作岗位后便很少维护

现在此项目已经出现大量的 Bug，并且代码时间过于久远所以很难调试

经过我们的讨论后，此项目即将在近期重写

在此期间由于此项目基本处于不可用状态，所以我们推荐使用另一库取代：https://github.com/Jeff-Tian/grpc-man

**Comment by jerryshell** [comment]
重写初版完成：https://github.com/grpcman/grpcman/commit/d7b9a281cb00d0365183f210bb74c1d3c7c1c9ad

**Comment by Ra9zer** [comment]
已经重写了完成了嘛

**Comment by jerryshell** [comment]
> 已经重写了完成了嘛

没有经过太多的测试，基本功能应该能用了
