### ISSUE TITLE
能留个联系方式吗 项目我跑不出跟你相同结果

### ISSUE THREAD

**Issue by Ra9zer** [grpcman/grpcman#8]

**Comment by jerryshell** [comment]
请提供一下报错信息

**Comment by Ra9zer** [comment]
![6fefe95049e589e6d1c1724d1997a94](https://user-images.githubusercontent.com/49937681/163589580-e05cfdc3-56a7-41b8-a541-23d5a5d6cbfd.png)

**Comment by Ra9zer** [comment]
是不是本地跑grpc官方demo的helloword的server 然后让grpcman访问

**Comment by Ra9zer** [comment]
有邮箱 或者qq vx吗 希望能指导一下 有偿

**Comment by zcyc** [comment]
我们重启了测试 server，你现在试试，其实就是 grpc 官方例子的 server。

**Comment by zcyc** [comment]
如果无法停止测试，点击上方删除任务，然后重新创建任务

**Comment by Ra9zer** [comment]
![image](https://user-images.githubusercontent.com/49937681/163592706-26ab09b3-bdc0-4b31-93e5-7f02198c08bd.png)

**Comment by Ra9zer** [comment]
服务器地址能再发一下吗

**Comment by jerryshell** [comment]
我们测试服的 DNS 在国外，所以 DNS 解析可能会有点问题

**Comment by jerryshell** [comment]
此项目 Bug 太多，将在近期重写，详情请看：https://github.com/grpcman/grpcman/issues/10

**Comment by Ra9zer** [comment]
我自己本地有跑server服务  
但是日志没有输出

**Comment by zcyc** [comment]
> 

程序有个bug，你得先输入你本地的服务地址，然后再选择 proto 文件。

这个bug 新版本解决。
